version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/itl
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  db:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: itl
      MYSQL_ROOT_PASSWORD: admin   # Cambiado de MYSQL_USER a MYSQL_ROOT_PASSWORD
